# Generated by Django 2.1.7 on 2019-02-16 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lounge_name', models.CharField(max_length=200)),
                ('lounge_description', models.TextField()),
                ('lounge_rep_1', models.CharField(max_length=200)),
                ('lounge_rep_2', models.CharField(max_length=200)),
                ('lounge_url', models.URLField()),
                ('lounge_funds', models.IntegerField()),
                ('interlounge_funds', models.IntegerField()),
                ('lounge_funds_remaining', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoungeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding', models.IntegerField()),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simslounge.Lounge')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_name', models.CharField(max_length=50)),
                ('proposal_description', models.TextField()),
                ('proposal_amount', models.IntegerField()),
                ('proposal_reg_funding', models.BooleanField()),
                ('proposal_passed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(max_length=200)),
                ('resident_kerb', models.CharField(max_length=20)),
                ('resident_funding', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simslounge.Resident'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_lounge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simslounge.Lounge'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_no',
            field=models.ManyToManyField(related_name='no_votes', to='simslounge.LoungeMember'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_yes',
            field=models.ManyToManyField(related_name='yes_votes', to='simslounge.LoungeMember'),
        ),
        migrations.AddField(
            model_name='loungemember',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simslounge.Resident'),
        ),
    ]
