# Generated by Django 2.1.7 on 2019-02-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simslounge', '0002_resident_resident_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lounge',
            name='lounge_funds_remaining',
        ),
        migrations.AlterField(
            model_name='lounge',
            name='lounge_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lounge',
            name='lounge_rep_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lounge',
            name='lounge_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='resident_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
