# Generated by Django 2.1.7 on 2019-02-17 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simslounge', '0004_auto_20190217_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='resident_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loungemember',
            name='lounge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='simslounge.Lounge'),
        ),
        migrations.AlterField(
            model_name='loungemember',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lounges', to='simslounge.Resident'),
        ),
    ]
